---
- hosts: all
  vars:
    composer_settings: "{{ lookup('file','../composer.json') | from_json }}"
  roles:
    - repo-remi
    - php_upgrade
  tasks:
    - name: Update composer dependencies for Visor
      composer:
        command: "{{ item }}"
        working_dir: "/vagrant/"
        # no_dev: false
      become: yes
      become_user: "vagrant" 
      with_items:
        - install
        - update 
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"  

