---
- hosts: all
  vars:
    composer_settings: "{{ lookup('file','../composer.json') | from_json }}"
  roles:
    - repo-remi
    - php_upgrade
  tasks:
    - name: Update composer dependencies for CIMS Usertool
      composer:
        command: "{{ item }}"
        working_dir: "/vagrant/"
        # no_dev: false
      become: yes
      become_user: "vagrant" 
      with_items:
        - install
        - update 
      args:
        chdir: "/vagrant/"
      environment:
        PATH: "/usr/local/bin:~/bin:{{ ansible_env.PATH }}"  
    - name: Install RPM required build packages
      yum: 
        name: "{{ item }}"
        state: latest
      with_items:
        - epel-release
        - git
        - ruby
        - ruby-devel
        - rubygems
        - rpm-build
    - name: Ensure the fpm gem installed
      command: gem install fpm
    - name: Build CIMS usertool RPM
      shell: "{{ item }}"
      with_items:
        - "vendor/bin/box build"
        - "rm -Rf bin/*.rpm"
        - "fpm --force -s dir -t rpm -n {{ composer_settings.name.split('/') | last | quote }} -v {{ composer_settings.version | quote }} --iteration {{ composer_settings.iteration | quote }}'1' --description {{ composer_settings.description | quote }} --vendor 'University of South Florida' --config-files '/usr/local/etc/cimsusertool/settings.yml' -p 'bin' 'bin/cimsusertool.phar'='/usr/local/bin/cimsusertool' 'config/settings.yml'='/usr/local/etc/cimsusertool/settings.yml'"
      args:
        chdir: "/vagrant/"
      environment:
        PATH: "/usr/local/bin:~/bin:{{ ansible_env.PATH }}"  
